// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitStats() {
  return window['go']['main']['App']['InitStats']();
}

export function UpdateCPUStats() {
  return window['go']['main']['App']['UpdateCPUStats']();
}
